/**
 * Generated from the Drafty API OpenAPI v1 contract.
 * Run `npm run api:types` after changing the API schema.
 * Do not edit this file directly.
 */
export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the current rankings compatibility payload.
         * @description The response body preserves the existing snake_case wire shape. This operation is governed by the v1 contract while the endpoint remains backward compatible.
         */
        get: operations["getLatestRankings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/draft-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or retrieve a local draft session. */
        post: operations["createDraftSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/draft-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        /** Return a local draft session. */
        get: operations["getDraftSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/draft-sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        get: operations["getDraftSessionEvents"];
        put?: never;
        post: operations["appendDraftSessionEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/draft-sessions/{session_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        /** Return the latest deterministic recommendation snapshot. */
        get: operations["getDraftRecommendations"];
        /** Persist a locally calculated recommendation snapshot. */
        put: operations["putDraftRecommendations"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/draft-sessions/{session_id}/opponent-forecast": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        /** Return the latest deterministic opponent forecast. */
        get: operations["getDraftOpponentForecast"];
        /** Persist a locally calculated opponent forecast. */
        put: operations["putDraftOpponentForecast"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/realtime/client-secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a short-lived OpenAI Realtime client secret.
         * @description Uses the server-side OpenAI API key and a server-owned session configuration. Standard API keys, model overrides, prompts, and arbitrary tool definitions are never accepted from the browser.
         */
        post: operations["createRealtimeClientSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranking-profiles-v2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List canonical ranking-profile-v2 records. */
        get: operations["listRankingProfilesV2"];
        put?: never;
        /** Create a canonical-v2-authoritative ranking profile. */
        post: operations["createRankingProfileV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranking-profiles-v2/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        /** Read the current canonical revision and mutation authority. */
        get: operations["getRankingProfileV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranking-profiles-v2/{profile_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save an immutable canonical v2 revision and explicitly promote legacy authority when needed. */
        post: operations["createRankingProfileV2Revision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranking-profiles-v2/{profile_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move the canonical current-revision pointer backward. */
        post: operations["undoRankingProfileV2Revision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranking-profiles-v2/{profile_id}/redo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move the canonical current-revision pointer forward. */
        post: operations["redoRankingProfileV2Revision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranking-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List local positional ranking profiles. */
        get: operations["listRankingProfiles"];
        put?: never;
        /** Create a named ranking profile and its first revision. */
        post: operations["createRankingProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranking-profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        /** Return the active revision of a ranking profile. */
        get: operations["getRankingProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranking-profiles/{profile_id}/rebase-preview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview a server-verified, deterministic, non-mutating profile rebase.
         * @description The server verifies the configured source/provider, last-good Phase 12A season/scoring/fingerprint and exact player ranks, plus player positions from its current player universe. Caller expected fingerprints are stale-request assertions only.
         */
        post: operations["previewRankingProfileRebase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranking-profiles/{profile_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save a new immutable ranking profile revision. */
        post: operations["createRankingProfileRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranking-profiles/{profile_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a profile to its preceding revision. */
        post: operations["undoRankingProfileRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranking-profiles/{profile_id}/redo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a profile to its next saved revision. */
        post: operations["redoRankingProfileRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranking-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured ranking sources and last-good status. */
        get: operations["listRankingSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranking-sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        /** Return one ranking source status. */
        get: operations["getRankingSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranking-sources/{source_id}/refresh-preview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview a bounded inline candidate without applying it.
         * @description Deterministic and non-mutating. No provider locator, filesystem path, transport override, apply, or promotion is accepted.
         */
        post: operations["previewRankingSourceRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data-readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return season availability and stored source-freshness evidence.
         * @description The API owns completed-versus-partial season classification. generated_at describes response construction time and is never source-freshness evidence.
         */
        get: operations["getDataReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/historical/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute a bounded historical group, filter, and sort query.
         * @description Accepts only versioned dimensions, metrics, filters, and declarative chart types. Arbitrary SQL and executable chart code are not accepted.
         */
        post: operations["executeHistoricalAnalysisQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/historical/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare weekly fantasy distributions for mapped players. */
        get: operations["getHistoricalComparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/historical/identity-misses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List nflverse players not mapped to canonical rankings IDs. */
        get: operations["getHistoricalIdentityMisses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/{player_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        /** Return bounded structured status events for a player. */
        get: operations["getPlayerStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
            code?: string;
        };
        HealthResponse: {
            /** @constant */
            status: "ok";
            rankings_source: string;
            /** Format: date-time */
            rankings_cached_at: string | null;
            rankings_season: number | null;
            player_count: number;
        };
        /** @enum {string} */
        SourceAvailability: "available" | "unavailable";
        RankingsReadiness: {
            availability: components["schemas"]["SourceAvailability"];
            season: number | null;
            /** Format: date-time */
            cached_at: string | null;
            source: string | null;
            player_count: number;
            fingerprint: string | null;
        };
        IdentityCatalogReadiness: {
            availability: components["schemas"]["SourceAvailability"];
            source: string | null;
            dataset: string | null;
            /** Format: uri */
            source_url: string | null;
            /** Format: date-time */
            retrieved_at: string | null;
            fingerprint: string | null;
            player_count: number;
        };
        /** @enum {string} */
        SeasonClassification: "completed" | "current_partial";
        ImportedWeeklySeasonReadiness: {
            season: number;
            classification: components["schemas"]["SeasonClassification"];
            /** Format: uri */
            source_url: string;
            fingerprint: string;
            /** Format: date-time */
            retrieved_at: string;
            row_count: number;
            identity_miss_count: number;
        };
        StatusSourceReadiness: {
            provider: string;
            dataset: string;
            season: number | null;
            /** @enum {string} */
            availability: "never_imported" | "available" | "unavailable";
            /** @enum {string} */
            freshness: "fresh" | "stale" | "unknown";
            /** @enum {string} */
            evidence: "none" | "status_event" | "import_run";
            /** Format: uri */
            source_url: string | null;
            fingerprint: string | null;
            /** Format: date-time */
            retrieved_at: string | null;
            record_count: number;
            reason: string | null;
        };
        DataReadinessResponse: {
            /** @constant */
            schema_version: 1;
            /**
             * Format: date-time
             * @description Response construction time; not source-freshness evidence.
             */
            generated_at: string;
            current_fantasy_season: number;
            completed_season_through: number;
            rankings: components["schemas"]["RankingsReadiness"];
            identity_catalog: components["schemas"]["IdentityCatalogReadiness"];
            imported_weekly_seasons: components["schemas"]["ImportedWeeklySeasonReadiness"][];
            completed_seasons: number[];
            current_partial_seasons: number[];
            historical_identity_miss_count: number;
            status_sources: components["schemas"]["StatusSourceReadiness"][];
        };
        /** @enum {string} */
        FantasyPosition: "QB" | "RB" | "WR" | "TE" | "DST" | "K" | "";
        FantasySettings: {
            ppr: boolean;
            num_teams: number;
            num_starting_qbs: number;
            num_starting_rbs: number;
            num_starting_wrs: number;
            num_starting_tes: number;
            num_flex_positions: number;
            num_bench_players: number;
        };
        Tier: {
            tier_number: number;
            upper_limit_player_idx: number;
            upper_limit_value: number;
            lower_limit_player_idx: number;
            lower_limit_value: number;
        };
        PlayerRanking: {
            player_id: string;
            ranker: string;
            position: components["schemas"]["FantasyPosition"];
            metric_value_ppr: number | null;
            metric_value_std: number | null;
            metric_value_half_ppr?: number | null;
            adp: number | null;
            standard_overall_rank: number | null;
            half_ppr_overall_rank?: number | null;
            ppr_overall_rank: number | null;
            standard_position_rank: number | null;
            standard_position_tier: components["schemas"]["Tier"] | null;
            half_ppr_position_rank?: number | null;
            half_ppr_position_tier?: components["schemas"]["Tier"] | null;
            ppr_position_rank: number | null;
            ppr_position_tier: components["schemas"]["Tier"] | null;
            source_position_tiers?: {
                [key: string]: number;
            };
        };
        EspnSourcePresence: {
            present_in_current_response: boolean;
            /** Format: date-time */
            last_seen_at: string | null;
            source_url: string | null;
            source_fingerprint: string | null;
            /** @enum {string} */
            reason: "present_in_current_response" | "not_present_in_current_response";
            last_known_rank: components["schemas"]["PlayerRanking"] | null;
        };
        PlayerSourcePresence: {
            espn: components["schemas"]["EspnSourcePresence"];
        };
        PlayerAvailability: {
            /** @enum {string} */
            state: "ranked_current" | "active_unranked" | "reserve" | "free_agent" | "unknown" | "inactive_confirmed";
            automatic_recommendation_eligible: boolean;
            source: string;
            source_url: string | null;
            /** Format: date-time */
            observed_at: string | null;
            reason: string;
            source_status: string | null;
        };
        /** @description Compatibility shape for the current cached PFR-derived records. This blob is not extended and will be replaced by nflverse endpoints. */
        LegacyHistoricalStats: {
            [key: string]: unknown;
        };
        PlayerOutlook: {
            text: string;
            /** @constant */
            source: "espn";
            season: number | null;
            /** Format: date-time */
            observed_at: string | null;
        };
        PlayerProfileNote: {
            note_id: string;
            subject: string;
            /** @enum {string} */
            scope: "player" | "team";
            /** @enum {string} */
            category: "good" | "bad" | "watch";
            /** @enum {string} */
            sentiment: "positive" | "negative" | "mixed" | "neutral";
            action_type: string;
            action_qualifier: string | null;
            summary: string;
            evidence: string | null;
            counterweight: string | null;
            practical_implication: string | null;
            speakers: string[];
            source: string;
            source_label: string;
            /** Format: uri */
            source_url: string;
            episode_id: string;
            episode_title: string;
            /** @enum {string} */
            coverage: "full-transcript" | "captions" | "transcript-derived" | "show-notes-only";
            /** @enum {string} */
            confidence: "high" | "medium" | "low";
            /** Format: date-time */
            published_at: string;
        };
        PlayerInjuryStatus: {
            status: string;
            injured: boolean;
            /** @constant */
            source: "espn";
            /** Format: date-time */
            observed_at: string;
        };
        Player: {
            id: string;
            first_name: string;
            last_name: string;
            full_name: string;
            team: string;
            position: components["schemas"]["FantasyPosition"];
            ranks: {
                [key: string]: components["schemas"]["PlayerRanking"];
            };
            historical_stats: {
                [key: string]: components["schemas"]["LegacyHistoricalStats"] | null;
            };
            source_presence?: components["schemas"]["PlayerSourcePresence"];
            availability?: components["schemas"]["PlayerAvailability"];
            outlook?: components["schemas"]["PlayerOutlook"] | null;
            profile_notes?: components["schemas"]["PlayerProfileNote"][];
            injury_status?: components["schemas"]["PlayerInjuryStatus"] | null;
        };
        ReplacementLevel: [
            number,
            number
        ];
        RankingSummary: {
            ranker: string;
            ppr: boolean;
            replacement_levels: {
                [key: string]: components["schemas"]["ReplacementLevel"];
            };
            std_devs: {
                [key: string]: number;
            };
            tiers: {
                [key: string]: components["schemas"]["Tier"][];
            };
        };
        RankingsResponse: {
            /** Format: date-time */
            cached_at: string;
            settings: components["schemas"]["FantasySettings"];
            players: components["schemas"]["Player"][];
            rankings_summaries: components["schemas"]["RankingSummary"][];
            all_data_rankers: string[];
            all_third_party_rankers: string[];
            season: number;
            ranking_sources: components["schemas"]["RankingArtifactSources"];
        };
        RankingArtifactSource: {
            id: string;
            provider_id: string;
            provider_name: string;
            ranker: string;
            publisher?: string;
            /** @enum {string} */
            ingestion_mode: "managed" | "user_import" | "reference_only";
            scoring_formats: ("standard" | "half_ppr" | "ppr")[];
            /** Format: uri */
            source_url: string;
            season: number;
            /** Format: date-time */
            retrieved_at: string;
            source_updated_at: string | null;
            fingerprint: string;
            raw_source_fingerprint: string;
            record_count: number;
            tier_method: string;
            source_native_tier_count: number;
        };
        RankingArtifactSources: {
            /** @constant */
            schema_version: 1;
            sources: components["schemas"]["RankingArtifactSource"][];
        };
        AnalysisSeasonRange: {
            start: number;
            end: number;
        };
        AnalysisSeasonSelection: components["schemas"]["AnalysisSeasonRange"] | number[];
        AnalysisFilter: {
            /** @enum {string} */
            field: "player_id" | "player_name" | "position" | "season" | "week" | "team" | "opponent" | "fantasy_points" | "attempts" | "passing_yards" | "carries" | "rushing_yards" | "receptions" | "targets" | "receiving_yards";
            /** @enum {string} */
            operator: "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "in" | "between";
            value: unknown;
        };
        AnalysisSort: {
            field: string;
            /** @enum {string} */
            direction: "asc" | "desc";
        };
        AnalysisVisualization: {
            /** @enum {string} */
            type: "line" | "bar" | "scatter" | "box" | "violin" | "density" | "heatmap";
            x: string;
            y: string;
            color?: string;
            facet?: string;
        };
        AnalysisQuery: {
            player_ids: string[];
            positions: ("QB" | "RB" | "WR" | "TE")[];
            seasons: components["schemas"]["AnalysisSeasonSelection"];
            weeks?: number[];
            scoring_profile_id: components["schemas"]["ScoringProfileId"];
            metrics: ("games" | "fantasy_points_mean" | "fantasy_points_total" | "fantasy_points_std_dev" | "fantasy_points_p10" | "fantasy_points_p50" | "fantasy_points_p90" | "attempts_total" | "passing_yards_total" | "carries_total" | "rushing_yards_total" | "receptions_total" | "targets_total" | "receiving_yards_total" | "touchdowns_total")[];
            /** @enum {string} */
            group_by: "player" | "position" | "season" | "week" | "opponent";
            filters: components["schemas"]["AnalysisFilter"][];
            sort: components["schemas"]["AnalysisSort"];
            limit: number;
            visualization: components["schemas"]["AnalysisVisualization"];
        };
        AnalysisValue: string | number;
        AnalysisRow: {
            dimensions: {
                [key: string]: components["schemas"]["AnalysisValue"];
            };
            metrics: {
                [key: string]: number;
            };
        };
        AnalysisColumns: {
            dimensions: string[];
            metrics: string[];
        };
        AnalysisQueryResponse: {
            query: components["schemas"]["AnalysisQuery"];
            scoring_profile: components["schemas"]["ScoringProfile"];
            sources: components["schemas"]["HistoricalSource"][];
            columns: components["schemas"]["AnalysisColumns"];
            visualization: components["schemas"]["AnalysisVisualization"];
            row_count: number;
            truncated: boolean;
            rows: components["schemas"]["AnalysisRow"][];
        };
        /**
         * @default ppr
         * @enum {string}
         */
        ScoringProfileId: "standard" | "half_ppr" | "ppr";
        HistoricalSource: {
            id: string;
            /** @constant */
            provider: "nflverse";
            /** @constant */
            dataset: "stats_player_week";
            sha256: string;
            /** Format: date-time */
            retrieved_at: string;
            /** @constant */
            schema_version: 1;
        };
        ScoringProfile: {
            id: components["schemas"]["ScoringProfileId"];
            weights: {
                [key: string]: number;
            };
        };
        PointDistribution: {
            games: number;
            mean: number;
            median: number;
            std_dev: number;
            minimum: number;
            p10: number;
            p25: number;
            p50: number;
            p75: number;
            p90: number;
            maximum: number;
        };
        HistoricalWeek: {
            season: number;
            week: number;
            team: string;
            opponent: string;
            points: number;
            contributions: {
                [key: string]: number;
            };
        };
        SeasonDistribution: {
            season: number;
            distribution: components["schemas"]["PointDistribution"];
        };
        HistoricalPlayerComparison: {
            player_id: string;
            player_name: string;
            position: string;
            distribution: components["schemas"]["PointDistribution"];
            season_distributions: components["schemas"]["SeasonDistribution"][];
            weeks: components["schemas"]["HistoricalWeek"][];
        };
        HistoricalComparisonResponse: {
            season: number;
            seasons: number[];
            source: components["schemas"]["HistoricalSource"];
            sources: components["schemas"]["HistoricalSource"][];
            scoring_profile: components["schemas"]["ScoringProfile"];
            identity_miss_count: number;
            players: components["schemas"]["HistoricalPlayerComparison"][];
        };
        IdentityMiss: {
            source_player_id: string;
            player_name: string;
            position: string;
            team: string;
            reason: string;
        };
        IdentityMissListResponse: {
            season: number;
            source_id: string;
            count: number;
            misses: components["schemas"]["IdentityMiss"][];
        };
        /** @enum {string} */
        RankingProfileV2ScoringType: "ppr" | "half_ppr" | "standard";
        RankingProfileV2Player: {
            player_id: string;
            user_tier: number;
        };
        RankingProfileV2Positions: {
            QB: components["schemas"]["RankingProfileV2Player"][];
            RB: components["schemas"]["RankingProfileV2Player"][];
            WR: components["schemas"]["RankingProfileV2Player"][];
            TE: components["schemas"]["RankingProfileV2Player"][];
        };
        RankingProfileUnresolvedPlayer: {
            player_id: string;
            /** @enum {string} */
            last_position: "QB" | "RB" | "WR" | "TE";
            last_user_rank: number;
            last_user_tier: number;
            /** @enum {string} */
            reason: "legacy_unknown" | "missing_from_target" | "position_changed";
        };
        RankingProfileProvenance: {
            /** @enum {string} */
            binding_state: "bound" | "legacy_unbound";
            base_source_id: string | null;
            base_provider_id: string | null;
            source_observation_fingerprint: string | null;
            source_season: number | null;
            source_scoring_type: components["schemas"]["RankingProfileV2ScoringType"] | null;
            player_universe_fingerprint: string | null;
        };
        /** @description Canonical profile v2. At most 500 unique player IDs may appear in total across all four active position arrays plus unresolved_players. */
        RankingProfileV2: {
            /** @constant */
            schema_version: 2;
            /** @constant */
            rebase_version: "profile_rebase_v1";
            scoring_type: components["schemas"]["RankingProfileV2ScoringType"];
            positions: components["schemas"]["RankingProfileV2Positions"];
            unresolved_players: components["schemas"]["RankingProfileUnresolvedPlayer"][];
            provenance: components["schemas"]["RankingProfileProvenance"];
        };
        /** @enum {string} */
        RankingProfileV2MutationAuthority: "legacy_v1" | "canonical_v2";
        RankingProfileV2Record: {
            id: string;
            name: string;
            scoring_profile: components["schemas"]["RankingProfileV2ScoringType"];
            source_ranker: string | null;
            /** @constant */
            projection_tier_method: "standard_deviation_v1";
            mutation_authority: components["schemas"]["RankingProfileV2MutationAuthority"];
            current_revision: number;
            max_revision: number;
            can_undo: boolean;
            can_redo: boolean;
            snapshot: components["schemas"]["RankingProfileV2"];
            history: components["schemas"]["RankingProfileRevision"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RankingProfileV2ListResponse: {
            profiles: components["schemas"]["RankingProfileV2Record"][];
        };
        RankingProfileV2CreateRequest: {
            id?: string;
            name: string;
            source_ranker?: string;
            snapshot: components["schemas"]["RankingProfileV2"];
        };
        RankingProfileV2RevisionRequest: {
            expected_revision: number;
            name?: string;
            reason?: string;
            snapshot: components["schemas"]["RankingProfileV2"];
        };
        RankingProfileV2MoveRevisionRequest: {
            expected_revision: number;
        };
        /** @enum {string} */
        RankingProfileV2ErrorCode: "invalid_request" | "invalid_profile_v2" | "profile_not_found" | "profile_conflict";
        RankingProfileV2ErrorResponse: {
            error: string;
            code: components["schemas"]["RankingProfileV2ErrorCode"];
        };
        RankingProfileRebaseTargetPlayer: {
            player_id: string;
            /** @enum {string} */
            position: "QB" | "RB" | "WR" | "TE";
            overall_rank: number;
        };
        /** @description Caller-supplied target assertions. The API independently binds these values to its configured source, Phase 12A last-good observation records, and server-held player-position universe before previewing. */
        RankingProfileRebaseTarget: {
            source_id: string;
            provider_id: string;
            season: number;
            scoring_type: components["schemas"]["RankingProfileV2ScoringType"];
            source_observation_fingerprint: string;
            expected_source_observation_fingerprint: string;
            player_universe_fingerprint: string;
            expected_player_universe_fingerprint: string;
            players: components["schemas"]["RankingProfileRebaseTargetPlayer"][];
        };
        RankingProfileRebasePreviewRequest: {
            expected_revision: number;
            target: components["schemas"]["RankingProfileRebaseTarget"];
        };
        RankingProfileRebaseCounts: {
            added: number;
            removed: number;
            position_conflicts: number;
            unresolved: number;
        };
        RankingProfileRebasePlayerIds: {
            added: string[];
            removed: string[];
            position_conflicts: string[];
            unresolved: string[];
        };
        RankingProfileRebasePreviewResponse: {
            /** @constant */
            schema_version: 1;
            /** @constant */
            rebase_version: "profile_rebase_v1";
            input_profile_fingerprint: string;
            output_profile_fingerprint: string;
            target_source_observation_fingerprint: string;
            target_player_universe_fingerprint: string;
            preview_key: string;
            /** @constant */
            logically_idempotent: true;
            would_change: boolean;
            counts: components["schemas"]["RankingProfileRebaseCounts"];
            player_ids: components["schemas"]["RankingProfileRebasePlayerIds"];
            profile: components["schemas"]["RankingProfileV2"];
        };
        RankingProfilePlayer: {
            player_id: string;
            rank: number;
            user_tier: number;
        };
        RankingProfilePositions: {
            QB: components["schemas"]["RankingProfilePlayer"][];
            RB: components["schemas"]["RankingProfilePlayer"][];
            WR: components["schemas"]["RankingProfilePlayer"][];
            TE: components["schemas"]["RankingProfilePlayer"][];
        };
        RankingProfileSnapshot: {
            /** @constant */
            schema_version: 1;
            positions: components["schemas"]["RankingProfilePositions"];
        };
        RankingProfileRevision: {
            revision: number;
            reason: string | null;
            /** Format: date-time */
            created_at: string;
        };
        RankingProfile: {
            id: string;
            name: string;
            scoring_profile: components["schemas"]["ScoringProfileId"];
            source_ranker: string | null;
            /** @constant */
            projection_tier_method: "standard_deviation_v1";
            current_revision: number;
            max_revision: number;
            can_undo: boolean;
            can_redo: boolean;
            snapshot: components["schemas"]["RankingProfileSnapshot"];
            history: components["schemas"]["RankingProfileRevision"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RankingProfileListResponse: {
            profiles: components["schemas"]["RankingProfile"][];
        };
        RankingProfileCreateRequest: {
            id?: string;
            name: string;
            scoring_profile: components["schemas"]["ScoringProfileId"];
            source_ranker?: string;
            snapshot: components["schemas"]["RankingProfileSnapshot"];
        };
        RankingProfileRevisionRequest: {
            expected_revision: number;
            name?: string;
            reason?: string;
            snapshot: components["schemas"]["RankingProfileSnapshot"];
        };
        RankingProfileMoveRevisionRequest: {
            expected_revision: number;
        };
        /** @enum {string} */
        RankingSourceAvailability: "available" | "stale" | "unavailable";
        RankingSourceStatus: {
            /** @constant */
            schema_version: 1;
            id: string;
            provider_id: string;
            provider_name: string;
            ranker?: string;
            /** @enum {string} */
            catalog_status?: "integrated" | "candidate" | "blocked";
            /** @enum {string} */
            ingestion_mode?: "managed" | "user_import" | "reference_only";
            scoring_formats?: ("standard" | "half_ppr" | "ppr")[];
            /** @enum {string} */
            tier_policy?: "none" | "drafty_derived" | "source_native" | "source_or_drafty_derived";
            /** Format: uri */
            source_url?: string;
            /** @enum {string} */
            authorization_status: "approved" | "unreviewed" | "restricted";
            /** @enum {string} */
            records_transport: "managed" | "user_import" | "reference_only" | "metadata_only";
            minimum_refresh_interval_hours: number | null;
            records_unavailable_reason: string | null;
            /** @enum {string} */
            storage_transport: "sqlite" | "artifact";
            /** @enum {string} */
            metadata_status: "recorded" | "not_recorded";
            availability: components["schemas"]["RankingSourceAvailability"];
            is_stale: boolean;
            /** Format: date-time */
            last_attempt_at: string | null;
            /** Format: date-time */
            last_success_at: string | null;
            last_success_provider_id: string | null;
            failure_reason: string | null;
            /** Format: date-time */
            retrieved_at: string | null;
            source_updated_at: string | null;
            season: number | null;
            scoring_type: components["schemas"]["ScoringProfileId"] | null;
            fingerprint: string | null;
            raw_source_fingerprint: string | null;
            record_count: number | null;
            tier_method: string | null;
            source_native_tier_count?: number;
        };
        RankingSourceListResponse: {
            sources: components["schemas"]["RankingSourceStatus"][];
        };
        RankingSourceCandidatePlayer: {
            player_id: string;
            overall_rank: number;
        };
        RankingSourceRefreshPreviewRequest: {
            /** Format: date-time */
            retrieved_at: string;
            season: number;
            scoring_type: components["schemas"]["ScoringProfileId"];
            players: components["schemas"]["RankingSourceCandidatePlayer"][];
        };
        RankingSourcePlayerDifference: {
            player_id: string;
            previous_rank: number;
            candidate_rank: number;
        };
        RankingSourceDifferences: {
            season_changed: boolean;
            scoring_type_changed: boolean;
            retrieval_time_changed: boolean;
            added_player_ids: string[];
            removed_player_ids: string[];
            changed: components["schemas"]["RankingSourcePlayerDifference"][];
        };
        RankingSourceRefreshPreviewResponse: {
            /** @constant */
            schema_version: 1;
            source: components["schemas"]["RankingSourceStatus"];
            candidate_fingerprint: string;
            idempotency_key: string;
            /** @constant */
            logically_idempotent: true;
            repeated_candidate: boolean;
            would_change: boolean;
            candidate_record_count: number;
            differences: components["schemas"]["RankingSourceDifferences"];
            affected_profile_player_ids: string[];
        };
        /** @enum {string} */
        DraftPlatform: "ESPN" | "NFL";
        DraftSessionCreateRequest: {
            id?: string;
            platform_draft_id?: string;
            title?: string;
            platform?: components["schemas"]["DraftPlatform"];
        };
        DraftSession: {
            id: string;
            platform_draft_id: string | null;
            title: string | null;
            platform: components["schemas"]["DraftPlatform"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CanonicalDraftPick: {
            playerId: string;
            overallPick: number;
            rosterIndex: number;
            name: string;
            team: string;
            position: string;
        };
        DraftPickRecordedEvent: {
            /** @constant */
            version: 1;
            /** @constant */
            kind: "draft-pick-recorded";
            eventId: string;
            draftId: string;
            draftTitle: string;
            platform: components["schemas"]["DraftPlatform"];
            capturedAt: number;
            pick: components["schemas"]["CanonicalDraftPick"];
        };
        CanonicalDraftEvent: components["schemas"]["DraftPickRecordedEvent"];
        DraftEventBatchRequest: {
            events: components["schemas"]["CanonicalDraftEvent"][];
        };
        DraftEventBatchResponse: {
            session_id: string;
            accepted_event_ids: string[];
            duplicate_event_ids: string[];
        };
        /** @enum {string} */
        AdvisorDraftPosition: "QB" | "RB" | "WR" | "TE";
        DraftRecommendationEvidence: {
            projected_floor: number;
            projected_median: number;
            projected_ceiling: number;
            replacement_level: number;
            points_above_replacement: number;
            marginal_lineup_points: number;
            bench_utility: number;
            tier_loss_if_deferred: number;
            survival_probability: number;
            positional_run_probability: number;
            tier_boundary_probability: number;
            user_tier: number | null;
            projection_tier: number | null;
            /** @enum {string} */
            roster_role: "open_starter" | "flex_upgrade" | "bench";
            flags: string[];
        };
        DraftRecommendationCandidate: {
            player_id: string;
            name: string;
            team: string;
            position: components["schemas"]["AdvisorDraftPosition"];
            position_rank: number;
            score: number;
            evidence: components["schemas"]["DraftRecommendationEvidence"];
        };
        DraftRecommendationSnapshot: {
            /** @constant */
            schema_version: 1;
            /** @constant */
            calculation_version: "deterministic_advisor_v1";
            source_event_count: number;
            input_fingerprint: string;
            /** Format: date-time */
            generated_at: string;
            current_pick: number;
            next_user_pick: number;
            /** @enum {string} */
            preferred_view: "tier_landscape" | "positional_bests" | "cross_position" | "intra_position";
            view_explanation: string;
            candidates: components["schemas"]["DraftRecommendationCandidate"][];
        };
        DraftRecommendationSnapshotResponse: {
            session_id: string;
            snapshot: components["schemas"]["DraftRecommendationSnapshot"];
        };
        OpponentPositionProbability: {
            position: components["schemas"]["AdvisorDraftPosition"];
            probability: number;
        };
        OpponentPlayerProbability: {
            player_id: string;
            name: string;
            position: components["schemas"]["AdvisorDraftPosition"];
            conditional_probability: number;
            overall_probability: number;
        };
        OpponentPickForecast: {
            overall_pick: number;
            roster_index: number;
            position_probabilities: components["schemas"]["OpponentPositionProbability"][];
            player_probabilities: components["schemas"]["OpponentPlayerProbability"][];
        };
        OpponentRunProbability: {
            position: components["schemas"]["AdvisorDraftPosition"];
            minimum_picks: number;
            probability: number;
        };
        OpponentTierBoundaryProbability: {
            position: components["schemas"]["AdvisorDraftPosition"];
            user_tier: number;
            player_ids: string[];
            probability: number;
        };
        OpponentForecastSnapshot: {
            /** @constant */
            schema_version: 1;
            /** @constant */
            calculation_version: "combined_opponent_v1";
            source_event_count: number;
            input_fingerprint: string;
            /** Format: date-time */
            generated_at: string;
            /** @enum {string} */
            model: "adp_only" | "need_only" | "combined";
            target_roster_index: number;
            picks: components["schemas"]["OpponentPickForecast"][];
            run_probabilities: components["schemas"]["OpponentRunProbability"][];
            tier_boundary_probabilities: components["schemas"]["OpponentTierBoundaryProbability"][];
        };
        OpponentForecastSnapshotResponse: {
            session_id: string;
            snapshot: components["schemas"]["OpponentForecastSnapshot"];
        };
        /** @enum {string} */
        RealtimeMode: "text" | "voice";
        RealtimeClientSecretRequest: {
            draft_session_id: string;
            mode: components["schemas"]["RealtimeMode"];
        };
        RealtimeClientSecretResponse: {
            value: string;
            expires_at: number;
            draft_session_id: string;
            realtime_session_id: string;
            mode: components["schemas"]["RealtimeMode"];
            model: string;
        };
        RealtimeGetDraftStateArguments: Record<string, never>;
        RealtimeGetRecommendationsArguments: Record<string, never>;
        RealtimeComparePlayersArguments: {
            player_ids: string[];
        };
        RealtimeProposeAnalysisViewArguments: {
            /** @enum {string} */
            view: "tier_landscape" | "positional_bests" | "cross_position" | "intra_position";
            explanation: string;
        };
        RealtimeProposeDraftPlanArguments: {
            text: string;
            explanation: string;
        };
        /** @enum {string} */
        AdvisorProposalStatus: "pending" | "accepted" | "rejected" | "stale";
        /** @enum {string} */
        AdvisorProposalKind: "analysis_view" | "draft_plan";
        AdvisorProposalPayload: {
            /** @enum {string} */
            view: "tier_landscape" | "positional_bests" | "cross_position" | "intra_position";
        } | {
            /** @constant */
            operation: "append";
            text: string;
        };
        AdvisorProposal: {
            /** @constant */
            schema_version: 1;
            id: string;
            draft_session_id: string;
            source_event_count: number;
            /** Format: date-time */
            created_at: string;
            kind: components["schemas"]["AdvisorProposalKind"];
            status: components["schemas"]["AdvisorProposalStatus"];
            title: string;
            explanation: string;
            payload: components["schemas"]["AdvisorProposalPayload"];
        };
        DraftPlanEntry: {
            id: string;
            proposal_id: string;
            text: string;
            source_event_count: number;
            /** Format: date-time */
            created_at: string;
        };
        DraftPlanDocument: {
            /** @constant */
            schema_version: 1;
            draft_session_id: string;
            revision: number;
            /** Format: date-time */
            updated_at: string;
            entries: components["schemas"]["DraftPlanEntry"][];
        };
        /** @enum {string} */
        PlayerStatusType: "injury" | "suspension" | "transaction" | "team_change" | "profile_news";
        /** @enum {string} */
        PlayerStatusImpact: "none" | "review" | "material";
        PlayerStatusObservation: {
            player_id: string;
            type: components["schemas"]["PlayerStatusType"];
            status: string;
            short_summary: string;
            source: string;
            /** Format: uri */
            source_url: string | null;
            /** Format: date-time */
            source_published_at: string | null;
            /** Format: date-time */
            fetched_at: string;
            confidence: number;
            recommendation_impact: components["schemas"]["PlayerStatusImpact"];
        };
        PlayerStatusEvent: {
            /** @constant */
            schema_version: 1;
            id: string;
            player_id: components["schemas"]["PlayerStatusObservation"]["player_id"];
            type: components["schemas"]["PlayerStatusType"];
            status: components["schemas"]["PlayerStatusObservation"]["status"];
            short_summary: components["schemas"]["PlayerStatusObservation"]["short_summary"];
            source: components["schemas"]["PlayerStatusObservation"]["source"];
            source_url: components["schemas"]["PlayerStatusObservation"]["source_url"];
            source_published_at: components["schemas"]["PlayerStatusObservation"]["source_published_at"];
            fetched_at: components["schemas"]["PlayerStatusObservation"]["fetched_at"];
            confidence: components["schemas"]["PlayerStatusObservation"]["confidence"];
            recommendation_impact: components["schemas"]["PlayerStatusImpact"];
            stale: boolean;
        };
        PlayerStatusResponse: {
            /** @constant */
            schema_version: 1;
            player_id: string;
            /** Format: date-time */
            last_updated_at: string | null;
            events: components["schemas"]["PlayerStatusEvent"][];
            summary?: components["schemas"]["PlayerStatusSummary"];
        };
        PlayerStatusSummary: {
            text: string | null;
            /** @enum {string} */
            method: "none" | "deterministic" | "openai";
            model: string | null;
            /** Format: date-time */
            generated_at: string | null;
            event_ids: string[];
        };
        DraftEventListResponse: {
            session_id: string;
            events: components["schemas"]["CanonicalDraftEvent"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API and rankings source status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getLatestRankings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current rankings. */
            200: {
                headers: {
                    "X-Drafty-Contract-Version"?: "1";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingsResponse"];
                };
            };
            /** @description No rankings are available. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createDraftSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftSessionCreateRequest"];
            };
        };
        responses: {
            /** @description The requested draft session already exists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSession"];
                };
            };
            /** @description The draft session was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSession"];
                };
            };
            /** @description The session request is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The session ID exists with different metadata. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDraftSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested draft session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSession"];
                };
            };
            /** @description The session does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDraftSessionEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical events in accepted order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftEventListResponse"];
                };
            };
            /** @description The session does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    appendDraftSessionEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftEventBatchRequest"];
            };
        };
        responses: {
            /** @description Events were accepted or identified as duplicates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftEventBatchResponse"];
                };
            };
            /** @description The event batch is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The session does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An event ID or draft identity conflicts with persisted data. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDraftRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The latest recommendation snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRecommendationSnapshotResponse"];
                };
            };
            /** @description The session or recommendation snapshot does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putDraftRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRecommendationSnapshot"];
            };
        };
        responses: {
            /** @description The recommendation snapshot was persisted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRecommendationSnapshotResponse"];
                };
            };
            /** @description The recommendation snapshot is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The session does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The snapshot is older than the persisted advisor state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDraftOpponentForecast: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The latest opponent forecast snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpponentForecastSnapshotResponse"];
                };
            };
            /** @description The session or opponent forecast does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putDraftOpponentForecast: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpponentForecastSnapshot"];
            };
        };
        responses: {
            /** @description The opponent forecast was persisted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpponentForecastSnapshotResponse"];
                };
            };
            /** @description The opponent forecast is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The session does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The snapshot is older than the persisted advisor state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRealtimeClientSecret: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RealtimeClientSecretRequest"];
            };
        };
        responses: {
            /** @description A short-lived client secret for the requested local draft session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealtimeClientSecretResponse"];
                };
            };
            /** @description The broker request is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The local draft session does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description OpenAI rejected or could not complete the client-secret request. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Realtime is not configured on the local API. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listRankingProfilesV2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical profiles ordered by most recent edit, including explicit mutation authority. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2ListResponse"];
                };
            };
        };
    };
    createRankingProfileV2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingProfileV2CreateRequest"];
            };
        };
        responses: {
            /** @description The canonical profile was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2Record"];
                };
            };
            /** @description The request or canonical snapshot is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2ErrorResponse"];
                };
            };
            /** @description The requested profile ID already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2ErrorResponse"];
                };
            };
        };
    };
    getRankingProfileV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The canonical profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2Record"];
                };
            };
            /** @description The profile does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2ErrorResponse"];
                };
            };
        };
    };
    createRankingProfileV2Revision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingProfileV2RevisionRequest"];
            };
        };
        responses: {
            /** @description The immutable canonical revision was saved. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2Record"];
                };
            };
            /** @description The request or canonical snapshot is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2ErrorResponse"];
                };
            };
            /** @description The profile does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2ErrorResponse"];
                };
            };
            /** @description The expected revision is stale or authority is unavailable. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2ErrorResponse"];
                };
            };
        };
    };
    undoRankingProfileV2Revision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingProfileV2MoveRevisionRequest"];
            };
        };
        responses: {
            /** @description The preceding canonical revision is current. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2Record"];
                };
            };
            /** @description The request is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2ErrorResponse"];
                };
            };
            /** @description The profile does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2ErrorResponse"];
                };
            };
            /** @description No undo exists or the expected revision is stale. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2ErrorResponse"];
                };
            };
        };
    };
    redoRankingProfileV2Revision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingProfileV2MoveRevisionRequest"];
            };
        };
        responses: {
            /** @description The next canonical revision is current. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2Record"];
                };
            };
            /** @description The request is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2ErrorResponse"];
                };
            };
            /** @description The profile does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2ErrorResponse"];
                };
            };
            /** @description No redo exists or the expected revision is stale. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileV2ErrorResponse"];
                };
            };
        };
    };
    listRankingProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranking profiles ordered by most recent edit. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileListResponse"];
                };
            };
        };
    };
    createRankingProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingProfileCreateRequest"];
            };
        };
        responses: {
            /** @description The ranking profile was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfile"];
                };
            };
            /** @description The profile or positional snapshot is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested profile ID already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRankingProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested ranking profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfile"];
                };
            };
            /** @description The profile does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    previewRankingProfileRebase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingProfileRebasePreviewRequest"];
            };
        };
        responses: {
            /** @description The deterministic rebase preview; no profile revision was written. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfileRebasePreviewResponse"];
                };
            };
            /** @description The request, profile conversion, or target metadata is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The profile does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The expected profile revision is stale. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRankingProfileRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingProfileRevisionRequest"];
            };
        };
        responses: {
            /** @description The new revision was saved. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfile"];
                };
            };
            /** @description The revision is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The profile does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The expected revision is stale. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    undoRankingProfileRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingProfileMoveRevisionRequest"];
            };
        };
        responses: {
            /** @description The preceding revision is active. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfile"];
                };
            };
            /** @description The request is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The profile does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description There is no undo revision or the expected revision is stale. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    redoRankingProfileRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingProfileMoveRevisionRequest"];
            };
        };
        responses: {
            /** @description The next revision is active. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingProfile"];
                };
            };
            /** @description The request is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The profile does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description There is no redo revision or the expected revision is stale. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listRankingSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All configured sources, including unavailable and stale sources. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingSourceListResponse"];
                };
            };
        };
    };
    getRankingSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Independent attempt, success, failure, and last-good evidence. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingSourceStatus"];
                };
            };
            /** @description The source is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    previewRankingSourceRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingSourceRefreshPreviewRequest"];
            };
        };
        responses: {
            /** @description A logically idempotent source and affected-profile diff. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingSourceRefreshPreviewResponse"];
                };
            };
            /** @description The inline candidate is malformed or outside its bounds. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The source is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDataReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned local data-readiness metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataReadinessResponse"];
                };
            };
        };
    };
    executeHistoricalAnalysisQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisQuery"];
            };
        };
        responses: {
            /** @description A bounded dataset and validated visualization specification. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisQueryResponse"];
                };
            };
            /** @description The query contains an unsupported field, metric, filter, sort, or visualization. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description One or more requested seasons have not been imported. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHistoricalComparison: {
        parameters: {
            query: {
                /** @description One to five comma-separated ESPN or canonical player IDs. */
                player_ids: string;
                season?: number;
                /** @description One to five comma-separated historical seasons. Takes precedence over season. */
                seasons?: string;
                scoring_profile?: components["schemas"]["ScoringProfileId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auditable weekly scoring and distributions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalComparisonResponse"];
                };
            };
            /** @description Invalid comparison parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested season has not been imported. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHistoricalIdentityMisses: {
        parameters: {
            query?: {
                season?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The visible identity-resolution queue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityMissListResponse"];
                };
            };
            /** @description The requested season has not been imported. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPlayerStatus: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status events, or an empty result when no provider data is available. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerStatusResponse"];
                };
            };
            /** @description Invalid player ID or limit. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
